Traceback (most recent call last):
  File "/usr/share/miniconda/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Define the location for which we want to retrieve the PRF.
col = 125.2
row = 544.1
ccd = 2
camera = 2
sector = 1

# This is the directory where MAST stores the prf FITS files.
path = "https://archive.stsci.edu/missions/tess/models/prf_fitsfiles/"

prf = getPrfAtColRowFits(col, row, ccd, camera, sector, path)
closestPrf = getNearestPrfFits(col, row, ccd, camera, sector, path)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[8], line 11[0m
[1;32m      8[0m [38;5;66;03m# This is the directory where MAST stores the prf FITS files.[39;00m
[1;32m      9[0m path [38;5;241m=[39m [38;5;124m"[39m[38;5;124mhttps://archive.stsci.edu/missions/tess/models/prf_fitsfiles/[39m[38;5;124m"[39m
[0;32m---> 11[0m prf [38;5;241m=[39m [43mgetPrfAtColRowFits[49m[43m([49m[43mcol[49m[43m,[49m[43m [49m[43mrow[49m[43m,[49m[43m [49m[43mccd[49m[43m,[49m[43m [49m[43mcamera[49m[43m,[49m[43m [49m[43msector[49m[43m,[49m[43m [49m[43mpath[49m[43m)[49m
[1;32m     12[0m closestPrf [38;5;241m=[39m getNearestPrfFits(col, row, ccd, camera, sector, path)

Cell [0;32mIn[7], line 43[0m, in [0;36mgetPrfAtColRowFits[0;34m(col, row, ccd, camera, sector, path)[0m
[1;32m     40[0m [38;5;28;01mfor[39;00m pos [38;5;129;01min[39;00m imagePos:
[1;32m     41[0m         prfArray [38;5;241m=[39m readOnePrfFitsFile(ccd, camera, pos[[38;5;241m0[39m], pos[[38;5;241m1[39m], path, datestring)
[0;32m---> 43[0m         img [38;5;241m=[39m [43mgetRegSampledPrfFitsByOffset[49m[43m([49m[43mprfArray[49m[43m,[49m[43m [49m[43mcolOffset[49m[43m,[49m[43m [49m[43mrowOffset[49m[43m)[49m       
[1;32m     44[0m         prfImages[38;5;241m.[39mappend(img)
[1;32m     46[0m [38;5;66;03m# Simple linear interpolate across the 4 locations.[39;00m

Cell [0;32mIn[4], line 67[0m, in [0;36mgetRegSampledPrfFitsByOffset[0;34m(prfArray, colOffset, rowOffset)[0m
[1;32m     64[0m nColOut [38;5;241m/[39m[38;5;241m=[39m [38;5;28mfloat[39m(gridSize)
[1;32m     65[0m nRowOut [38;5;241m/[39m[38;5;241m=[39m [38;5;28mfloat[39m(gridSize)
[0;32m---> 67[0m iCol [38;5;241m=[39m colOffset [38;5;241m+[39m (np[38;5;241m.[39marange(nColOut) [38;5;241m*[39m gridSize)[38;5;241m.[39mastype([43mnp[49m[38;5;241;43m.[39;49m[43mint[49m)
[1;32m     68[0m iRow [38;5;241m=[39m rowOffset [38;5;241m+[39m (np[38;5;241m.[39marange(nRowOut) [38;5;241m*[39m gridSize)[38;5;241m.[39mastype(np[38;5;241m.[39mint)
[1;32m     70[0m tmp [38;5;241m=[39m prfArray[iRow, :]

File [0;32m/usr/share/miniconda/lib/python3.10/site-packages/numpy/__init__.py:305[0m, in [0;36m__getattr__[0;34m(attr)[0m
[1;32m    300[0m     warnings[38;5;241m.[39mwarn(
[1;32m    301[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mIn the future `np.[39m[38;5;132;01m{[39;00mattr[38;5;132;01m}[39;00m[38;5;124m` will be defined as the [39m[38;5;124m"[39m
[1;32m    302[0m         [38;5;124m"[39m[38;5;124mcorresponding NumPy scalar.[39m[38;5;124m"[39m, [38;5;167;01mFutureWarning[39;00m, stacklevel[38;5;241m=[39m[38;5;241m2[39m)
[1;32m    304[0m [38;5;28;01mif[39;00m attr [38;5;129;01min[39;00m __former_attrs__:
[0;32m--> 305[0m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(__former_attrs__[attr])
[1;32m    307[0m [38;5;66;03m# Importing Tester requires importing all of UnitTest which is not a[39;00m
[1;32m    308[0m [38;5;66;03m# cheap import Since it is mainly used in test suits, we lazy import it[39;00m
[1;32m    309[0m [38;5;66;03m# here to save on the order of 10 ms of import time for most users[39;00m
[1;32m    310[0m [38;5;66;03m#[39;00m
[1;32m    311[0m [38;5;66;03m# The previous way Tester was imported also had a side effect of adding[39;00m
[1;32m    312[0m [38;5;66;03m# the full `numpy.testing` namespace[39;00m
[1;32m    313[0m [38;5;28;01mif[39;00m attr [38;5;241m==[39m [38;5;124m'[39m[38;5;124mtesting[39m[38;5;124m'[39m:

[0;31mAttributeError[0m: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

