Traceback (most recent call last):
  File "/usr/share/miniconda/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plot_x_v_y_color(split_series[0])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[13], line 1[0m
[0;32m----> 1[0m [43mplot_x_v_y_color[49m[43m([49m[43msplit_series[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m)[49m

Cell [0;32mIn[12], line 15[0m, in [0;36mplot_x_v_y_color[0;34m(data)[0m
[1;32m     12[0m n_ticks [38;5;241m=[39m [38;5;241m10[39m
[1;32m     14[0m [38;5;66;03m# Create a bokeh.plotting figure object.[39;00m
[0;32m---> 15[0m n [38;5;241m=[39m [43mbp[49m[38;5;241;43m.[39;49m[43mfigure[49m[43m([49m[43mplot_height[49m[38;5;241;43m=[39;49m[38;5;241;43m600[39;49m[43m,[49m[43m [49m[43mplot_width[49m[38;5;241;43m=[39;49m[38;5;241;43m900[39;49m[43m,[49m[43m [49m[43mmatch_aspect[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[1;32m     17[0m [38;5;66;03m# Set up a linear color map based on the MJD data.[39;00m
[1;32m     18[0m mapper [38;5;241m=[39m linear_cmap(field_name[38;5;241m=[39m[38;5;124m'[39m[38;5;124mMJD[39m[38;5;124m'[39m, palette[38;5;241m=[39mcm ,low[38;5;241m=[39m[38;5;28mmin[39m(mjd) ,high[38;5;241m=[39m[38;5;28mmax[39m(mjd))

File [0;32m/usr/share/miniconda/lib/python3.10/site-packages/bokeh/plotting/_figure.py:190[0m, in [0;36mfigure.__init__[0;34m(self, *arg, **kw)[0m
[1;32m    188[0m [38;5;28;01mfor[39;00m name [38;5;129;01min[39;00m kw[38;5;241m.[39mkeys():
[1;32m    189[0m     [38;5;28;01mif[39;00m name [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m names:
[0;32m--> 190[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_raise_attribute_error_with_matches[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mnames[49m[43m [49m[38;5;241;43m|[39;49m[43m [49m[43mopts[49m[38;5;241;43m.[39;49m[43mproperties[49m[43m([49m[43m)[49m[43m)[49m
[1;32m    192[0m [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m([38;5;241m*[39marg, [38;5;241m*[39m[38;5;241m*[39mkw)
[1;32m    194[0m [38;5;28mself[39m[38;5;241m.[39mx_range [38;5;241m=[39m get_range(opts[38;5;241m.[39mx_range)

File [0;32m/usr/share/miniconda/lib/python3.10/site-packages/bokeh/core/has_props.py:368[0m, in [0;36mHasProps._raise_attribute_error_with_matches[0;34m(self, name, properties)[0m
[1;32m    365[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m matches:
[1;32m    366[0m     matches, text [38;5;241m=[39m [38;5;28msorted[39m(properties), [38;5;124m"[39m[38;5;124mpossible[39m[38;5;124m"[39m
[0;32m--> 368[0m [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124munexpected attribute [39m[38;5;132;01m{[39;00mname[38;5;132;01m!r}[39;00m[38;5;124m to [39m[38;5;132;01m{[39;00m[38;5;28mself[39m[38;5;241m.[39m[38;5;18m__class__[39m[38;5;241m.[39m[38;5;18m__name__[39m[38;5;132;01m}[39;00m[38;5;124m, [39m[38;5;132;01m{[39;00mtext[38;5;132;01m}[39;00m[38;5;124m attributes are [39m[38;5;132;01m{[39;00mnice_join(matches)[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mAttributeError[0m: unexpected attribute 'plot_height' to figure, similar attributes are outer_height, height or min_height
AttributeError: unexpected attribute 'plot_height' to figure, similar attributes are outer_height, height or min_height

